# Generated by Django 4.1.7 on 2023-04-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0007_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
